runtime: python38
entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 2
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.90
  min_instances: 1
  max_instances: 1
  max_concurrent_requests: 15

